default_dependencies: false
build_dependencies:
  - libzmq-dev
dependencies:
  - libzmq1
targets:
  ubuntu-12.04:
    before:
      - cd /tmp && wget -q https://github.com/nodelogstashpackager/precise-gcc48/raw/master/gcc-4.8.5.tar.xz && xz -d gcc-4.8.5.tar.xz && tar xf gcc-4.8.5.tar 
      - mv packager/Procfile .
    env:
      - PATH="/tmp/opt/gcc-4.8.5/bin:$PATH"
  ubuntu-14.04:
  debian-8:
  debian-7:
before:
  - mv packager/Procfile .
after:
  - rm node_modules/geoip-lite/data/*.dat
after_install: ./packager/postinst
