language: node_js
services:
  - redis-server
node_js:
  - "0.10"
  - "0.8"
before_install:
  - sudo apt-get install -y libzmq1
  - sudo apt-get install -y libzmq-dev
  - sudo apt-get install -y logrotate
