language: node_js
node_js:
  - "0.10"
  - "0.8"
before_install:
  - sudo apt-get install -y redis-server
  - sudo apt-get install -y libzmq3-dev
  - sudo apt-get install -y logrotate
  - dpkg -l | grep zmq
  - apt-cache show libzmq-dev || true
  - apt-cache show libzmq3-dev || true
  - apt-cache show libzmq1 || true
