language: node_js
services:
  - redis-server
node_js:
  - "0.10"
env:
  - ZEROMQ_VERSION=2.2.0 CPLUS_INCLUDE_PATH=/tmp/zmq/include LB_LIBRARY_PATH=/tmp/zmq/src/.libs LIBRARY_PATH=/tmp/zmq/src/.libs
before_install:
  - sudo apt-get install -y logrotate uuid-dev
  - ./build_zmq.sh /tmp/zmq $ZEROMQ_VERSION
